--------------- 장바구니 ---------------

-- 더미데이터

-- 옵션
INSERT INTO TB_OPTION (OPT_NO, OPT_NAME, OPT_VALUE, OPT_ADD_PRICE, REMAIN_QTY, PROD_NO)
VALUES (1, 'Option1', 'Value1', 1000, 100, 9);
INSERT INTO TB_OPTION (OPT_NO, OPT_NAME, OPT_VALUE, OPT_ADD_PRICE, REMAIN_QTY, PROD_NO)
VALUES (2, 'Option2', 'Value2', 2000, 200, 10);
INSERT INTO TB_OPTION (OPT_NO, OPT_NAME, OPT_VALUE, OPT_ADD_PRICE, REMAIN_QTY, PROD_NO)
VALUES (3, 'Option3', 'Value3', 3000, 150, 11);
INSERT INTO TB_OPTION (OPT_NO, OPT_NAME, OPT_VALUE, OPT_ADD_PRICE, REMAIN_QTY, PROD_NO)
VALUES (4, 'Option4', 'Value4', 4000, 50, 11);
INSERT INTO TB_OPTION (OPT_NO, OPT_NAME, OPT_VALUE, OPT_ADD_PRICE, REMAIN_QTY, PROD_NO)
VALUES (5, 'Option5', 'Value5', 5000, 75, 11);
-- 장바구니
INSERT INTO TB_CART (CART_NO, MEMBER_ID, PROD_NO, OPT_NO, CART_QTY) VALUES (SEQ_CART_NO.NEXTVAL, 'user1', 9, 1, 3);
INSERT INTO TB_CART (CART_NO, MEMBER_ID, PROD_NO, OPT_NO, CART_QTY) VALUES (SEQ_CART_NO.NEXTVAL, 'admin', 10, 2, 1);
INSERT INTO TB_CART (CART_NO, MEMBER_ID, PROD_NO, OPT_NO, CART_QTY) VALUES (SEQ_CART_NO.NEXTVAL, 'admin', 11, 3, 3);
INSERT INTO TB_CART (CART_NO, MEMBER_ID, PROD_NO, OPT_NO, CART_QTY) VALUES (SEQ_CART_NO.NEXTVAL, 'admin', 11, 4, 9);
INSERT INTO TB_CART (CART_NO, MEMBER_ID, PROD_NO, OPT_NO, CART_QTY) VALUES (SEQ_CART_NO.NEXTVAL, 'admin', 11, 5, 5);
COMMIT;


-- 1. 장바구니 전체 개수 조회용 쿼리문
SELECT COUNT(*)
  FROM TB_CART
 WHERE CART_QTY >= 1
 
-- 2. 장바구니 목록 조회용 쿼리문
SELECT C.CART_NO
     , P.PROD_NAME
     , O.OPT_NAME
     , C.CART_QTY
     , P.PROD_PRICE
  FROM TB_CART C
  LEFT JOIN TB_PRODUCT P ON (C.PROD_NO = P.PROD_NO)
  LEFT JOIN TB_OPTION O ON (C.OPT_NO = O.OPT_NO)
 WHERE C.MEMBER_ID = #{memberId}
 ORDER BY C.CART_NO DESC;
 
-- 3. 장바구니 X버튼으로 1개 상품만 삭제
DELETE
  FROM TB_CART
 WHERE CART_NO IN (${cartNo})

-- 4. 장바구니 선택 삭제
DELETE
  FROM TB_CART
 WHERE CART_NO IN
<foreach collection="cartNoList" item="cartNos" separator="," open="(" close=")">
    #{cartNo}
</foreach>

-- 옵션 조회 (예원이가 할 게 아닌듯..?)
SELECT O.OPT_NAME
  FROM TB_OPTION O
  LEFT JOIN TB_PRODUCT P ON O.PROD_NO = P.PROD_NO
 WHERE P.PROD_NO = 105
 ORDER BY O.OPT_NO DESC
 
-- 옵션 변경
UPDATE TB_CART
  SET OPT_NO = ?
WHERE CART_NO = ?