-- 회원 생일컬럼 제약조건 변경구문-- 
ALTER TABLE TB_MEMBER
MODIFY BIRTHDATE DEFAULT NULL;

-- 회원 등급컬럼 제약조건 변경구문-- 
ALTER TABLE TB_MEMBER
          MODIFY GRADE_NAME  DEFAULT 'BABY';
         
-- 회원 배송지테이블 컬럼 추가 구문 --
ALTER TABLE TB_DELIVERY
ADD POSTCODE VARCHAR2(10);

ALTER TABLE TB_DELIVERY
          MODIFY POSTCODE  NOT NULL;
          
ALTER TABLE TB_DELIVERY     
ADD DETAIL_ADDRESS VARCHAR(255) ;  

-- 상품 테이블 컬럼 추가 구문 --
ALTER TABLE TB_PRODUCT
ADD (SUBCATEGORY_NAME VARCHAR2(60) NOT NULL);

-- 이메일 인증 테이블 컬럼 수정 구문 
ALTER TABLE TB_CERT_EMAIL
MODIFY (CERT_EMAIL VARCHAR2(100 BYTE));

-- 리뷰 테이블 타이틀 컬럼 삭제 구문 --
ALTER TABLE TB_REVIEW DROP COLUMN REV_TITLE;

-- 옵션 테이블 밸류값에 NULL 가능하도록 수정 --
ALTER TABLE TB_OPTION MODIFY OPT_VALUE NULL;

-- 1:1문의 테이블 컬럼 수정 구문
ALTER TABLE TB_INQUIRY DROP COLUMN INQUIRY_TITLE;
