-- 회원 생일컬럼 제약조건 변경구문-- 
ALTER TABLE TB_MEMBER
MODIFY BIRTHDATE DEFAULT NULL;

-- 회원 등급컬럼 제약조건 변경구문-- 
ALTER TABLE TB_MEMBER
          MODIFY GRADE_NAME  DEFAULT 'BABY';
--카카오 회원 가입시 아이디 컬럼, 로그인방식 컬럼 추가구문 --
ALTER TABLE TB_MEMBER
ADD SNS_ID VARCHAR2(20);

ALTER TABLE TB_MEMBER
ADD LOGIN_TYPE VARCHAR2(20) DEFAULT 'normal';

-- 회원 비밀번호 컬럼 제약조건 변경--
ALTER TABLE TB_MEMBER 
MODIFY MEMBER_PWD NULL;

         
-- 회원 배송지테이블 컬럼 추가 구문 --
ALTER TABLE TB_DELIVERY
ADD POSTCODE VARCHAR2(10);

ALTER TABLE TB_DELIVERY
          MODIFY POSTCODE  NOT NULL;
          
ALTER TABLE TB_DELIVERY     
ADD DETAIL_ADDRESS VARCHAR(255) ;  

-- 상품 테이블 컬럼 추가 구문 --
ALTER TABLE TB_PRODUCT
ADD (SUBCATEGORY_NAME VARCHAR2(60) NOT NULL);

-- 이메일 인증 테이블 컬럼 수정 구문 
ALTER TABLE TB_CERT_EMAIL
MODIFY (CERT_EMAIL VARCHAR2(100 BYTE));

-- 리뷰 테이블 타이틀 컬럼 삭제 구문 --
ALTER TABLE TB_REVIEW DROP COLUMN REV_TITLE;

-- 옵션 테이블 밸류값에 NULL 가능하도록 수정 --
ALTER TABLE TB_OPTION MODIFY OPT_VALUE NULL;

-- 1:1문의 테이블 컬럼 수정 구문
ALTER TABLE TB_INQUIRY DROP COLUMN INQUIRY_TITLE;

-- 미생성 시퀀스 생성 구문
CREATE SEQUENCE SEQ_SERIAL_NO;

-- 리뷰 테이블 드랍, 시퀀스 드랍, 시퀀스 생성, 리뷰 재생성
DROP TABLE TB_REVIEW CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_REV_NO;
CREATE SEQUENCE SEQ_REV_NO;
CREATE TABLE TB_REVIEW (
    REV_NO NUMBER NOT NULL,
    REV_CONTENT VARCHAR2(1500) NOT NULL,
    REV_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    REV_RATING NUMBER DEFAULT 0,
    REV_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
    SERIAL_NO VARCHAR2(30) NOT NULL,                   -- 주문 상세 번호 (TB_PRODUCT_ORDER)
    MEMBER_ID VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_REVIEW PRIMARY KEY (REV_NO),
    CONSTRAINT FK_SERIAL_TO_REVIEW FOREIGN KEY (SERIAL_NO) REFERENCES TB_PRODUCT_ORDER (SERIAL_NO),       -- FOREIGN KEY: TB_PRODUCT_ORDER 참조
    CONSTRAINT FK_MEMBER_TO_REVIEW FOREIGN KEY (MEMBER_ID) REFERENCES TB_MEMBER (MEMBER_ID)
);
COMMENT ON COLUMN TB_REVIEW.REV_NO IS '리뷰 번호';
COMMENT ON COLUMN TB_REVIEW.REV_CONTENT IS '리뷰 내용';
COMMENT ON COLUMN TB_REVIEW.REV_ENROLL_DATE IS '리뷰 등록일';
COMMENT ON COLUMN TB_REVIEW.REV_RATING IS '리뷰 평점';
COMMENT ON COLUMN TB_REVIEW.REV_STATUS IS '리뷰 상태값';
COMMENT ON COLUMN TB_REVIEW.SERIAL_NO IS '주문 상세 번호';
COMMENT ON COLUMN TB_REVIEW.MEMBER_ID IS '회원 아이디';

----  배송지테이블 배송지명컬럼 추가 구문 --
ALTER TABLE TB_DELIVERY
ADD DELI_NICKNAME VARCHAR2(30);

COMMENT ON COLUMN  TB_DELIVERY.DELI_NICKNAME IS '배송지명';

-- 배송지테이블 집주소여부컬럼 추가 구문--
ALTER TABLE TB_DELIVERY
ADD HOME_ADDRESS_YN CHAR(1) DEFAULT 'Y';

COMMENT ON COLUMN  TB_DELIVERY.HOME_ADDRESS_YN  IS '집주소여부';

-- 찜 테이블명 변경
RENAME TB_WISHI TO TB_WISH;

ALTER TABLE TB_PRODUCT
MODIFY PROD_ORIGIN VARCHAR2(3900 BYTE);

ALTER TABLE TB_PRODUCT
MODIFY PROD_CAUTION VARCHAR2(3900 BYTE);


COMMIT;